# Generated by Django 2.2.7 on 2020-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20201023_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Img',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
