# Generated by Django 2.2.7 on 2020-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_food_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='Exercise_text',
            field=models.CharField(blank=True, max_length=999999),
        ),
        migrations.AlterField(
            model_name='food',
            name='How_text',
            field=models.CharField(blank=True, max_length=999999),
        ),
        migrations.AlterField(
            model_name='food',
            name='Raw_text',
            field=models.CharField(blank=True, max_length=999999),
        ),
    ]
